// Renders the shared chrome into each page's HTML source.
//
// It used to be injected at runtime by chrome.js, so a page loaded without
// JavaScript had no header, no footer, no official banner and no skip link —
// unbranded body copy with nothing identifying it as a government service.
// GitHub Pages cannot run a server, so the only way for the chrome to survive
// with script unavailable is for it to be in the file.
//
// Idempotent: generated regions are delimited by comment markers and replaced
// on each run. `npm run check:pages` fails if a committed page has drifted.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import {
  skipLink,
  officialBanner,
  header,
  alphaBanner,
  footer,
  breadcrumbs,
  runtime,
  noScript,
} from "./chrome.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");

// The user-facing pages. job-letter-request.html is the superseded single-file
// prototype and is deliberately not in this list.
const PAGES = [
  "index.html",
  "request.html",
  "sent.html",
  "verify.html",
  "privacy.html",
  "accessibility.html",
  "cookies.html",
  "contact.html",
  "terms.html",
  "not-found.html",
];

const region = (name, body) =>
  `<!-- govbb:${name} — generated by scripts/build-pages.js, do not edit -->${body}\n<!-- /govbb:${name} -->`;

function regionRe(name) {
  return new RegExp(`<!-- govbb:${name}[^]*?<!-- /govbb:${name} -->`, "m");
}

function replaceRegion(html, name, body) {
  const re = regionRe(name);
  const rendered = region(name, body);
  if (re.test(html)) return html.replace(re, rendered);
  return null; // caller inserts it
}

// A region whose source declaration has been removed has to go, or it is
// frozen into the page forever — and --check would compare the generated
// output against the committed file and call the orphan "up to date".
function dropRegion(html, name) {
  const re = regionRe(name);
  return re.test(html) ? html.replace(re, "").replace(/\n[ \t]*\n[ \t]*\n/g, "\n\n") : html;
}

// Pages sit at the site root and link to each other relatively, which works on
// both Vercel (domain root) and Pages (project subpath). Kept as a seam so the
// admin pages, one level down, can reuse the same templates with "../".
const toPagePath = (s) => s.replace(/\{\{base\}\}/g, "");

// Give the request form a real action and method so it works without script.
// app.js calls preventDefault() and uses the JSON endpoint when script runs,
// so this is the fallback rather than the normal path.
//
// Same-origin on purpose. An absolute URL to the deploy would also let the
// GitHub Pages demo submit, but it would mean a local no-JS submit posting to
// production and issuing a real letter, which is not a trade worth making to
// paper over a static host that structurally cannot process a POST.
function buildForm(html) {
  return html.replace(
    /<form id="request-form"[^>]*novalidate>/,
    `<form id="request-form" method="post" action="/api/request-letter-form" novalidate>`
  );
}

// Every published template — landing, single question, multiple questions,
// confirmation — puts content directly inside
// <main class="govbb-width-container govbb-main-wrapper">, with no grid row
// and no column. /styles/layout.md says body content belongs in
// govbb-grid-column-two-thirds instead. The two disagree, and the templates win
// for the page type you are building; the disagreement is in the PR for the
// design team. govbb-main-wrapper already caps p/ul/ol/dl at --govbb-measure,
// so the reading width is handled without the grid.
//
// page-flow supplies the rhythm between blocks. The design system resets
// h1-h6, p and ul to margin-block:0 and ships no flow rule outside
// .govbb-prose, so with content directly in main every block would otherwise
// sit flush against the next.
function buildMain(html) {
  const openTag = html.match(/<main\b[^>]*>/);
  if (!openTag) return html;

  const crumbAttr = openTag[0].match(/data-breadcrumbs='([^']*)'/);
  const needsAttr = openTag[0].match(/data-needs-js="([^"]*)"/);
  const attrs =
    (crumbAttr ? ` data-breadcrumbs='${crumbAttr[1]}'` : "") +
    (needsAttr ? ` data-needs-js="${needsAttr[1]}"` : "");

  html = html.replace(
    openTag[0],
    `<main class="govbb-width-container govbb-main-wrapper page-flow" id="main-content" tabindex="-1"${attrs}>`
  );

  // Unwrap the grid row and column this used to emit.
  html = html
    .replace(/\s*<div class="govbb-grid-row">\s*\n\s*<div class="govbb-grid-column-two-thirds">/, "")
    .replace(/\s*<\/div>\s*\n\s*<\/div>\s*\n(\s*)<\/main>/, "\n$1</main>");

  return html;
}

function buildPage(file) {
  const p = path.join(ROOT, file);
  let html = fs.readFileSync(p, "utf-8");

  html = buildMain(html);
  html = buildForm(html);

  // The runtime injector is gone; its markup is now in the file.
  html = html.replace(/\s*<script src="chrome\.js"><\/script>/g, "");

  const top = toPagePath(skipLink + officialBanner + header + alphaBanner);
  const bottom = toPagePath(footer + runtime);

  const withTop = replaceRegion(html, "chrome-top", top);
  html =
    withTop ??
    html.replace(/(<body[^>]*>)/, `$1\n${region("chrome-top", top)}`);

  const withBottom = replaceRegion(html, "chrome-bottom", bottom);
  html =
    withBottom ??
    html.replace(/<\/body>/, `${region("chrome-bottom", bottom)}\n</body>`);

  // Breadcrumbs are declared per page on <main data-breadcrumbs>, and rendered
  // here so the trail is in the source too.
  const declared = html.match(/data-breadcrumbs='([^']*)'/);
  const crumbs = declared
    ? toPagePath(breadcrumbs(JSON.parse(declared[1])))
    : "";
  if (crumbs) {
    const withCrumbs = replaceRegion(html, "breadcrumbs", crumbs);
    html =
      withCrumbs ??
      html.replace(
        /(<main\b[^>]*>)/,
        `$1\n    ${region("breadcrumbs", crumbs)}`
      );
  } else {
    html = dropRegion(html, "breadcrumbs");
  }

  // Pages that declare data-needs-js get the JavaScript-disabled notice, so a
  // visitor without script is told what to do rather than left on a shell.
  const needs = html.match(/data-needs-js="([^"]*)"/);
  if (needs) {
    const block = toPagePath(noScript(needs[1]));
    const withNs = replaceRegion(html, "noscript", block);
    // Anchor on <main>, not on a grid column — the columns went when the page
    // shape was flattened to match the templates, and this insertion silently
    // did nothing for a while because its anchor no longer existed.
    html =
      withNs ??
      html.replace(/(<main\b[^>]*>)/, `$1\n    ${region("noscript", block)}`);
  } else {
    html = dropRegion(html, "noscript");
  }

  return { path: p, html };
}

const check = process.argv.includes("--check");
let changed = 0;
const stale = [];

for (const file of PAGES) {
  const { path: p, html } = buildPage(file);
  const current = fs.readFileSync(p, "utf-8");
  if (current === html) continue;
  if (check) {
    stale.push(file);
  } else {
    fs.writeFileSync(p, html);
    changed++;
  }
}

if (check) {
  if (stale.length) {
    console.error(
      `${stale.length} page(s) out of date with scripts/chrome.js:\n  ` +
        stale.join("\n  ") +
        `\nRun \`npm run build:pages\` and commit the result.`
    );
    process.exit(1);
  }
  console.log(`all ${PAGES.length} pages are up to date`);
} else {
  console.log(`chrome rendered into ${changed} of ${PAGES.length} page(s)`);
}
