// Renders the shared chrome into each page's HTML source.
//
// It used to be injected at runtime by chrome.js, so a page loaded without
// JavaScript had no header, no footer, no official banner and no skip link —
// unbranded body copy with nothing identifying it as a government service.
// GitHub Pages cannot run a server, so the only way for the chrome to survive
// with script unavailable is for it to be in the file.
//
// Idempotent: generated regions are delimited by comment markers and replaced
// on each run. `npm run check:pages` fails if a committed page has drifted.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import {
  skipLink,
  officialBanner,
  header,
  alphaBanner,
  footer,
  breadcrumbs,
  runtime,
  noScript,
} from "./chrome.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");

// The user-facing pages. job-letter-request.html is the superseded single-file
// prototype and is deliberately not in this list.
const PAGES = [
  "index.html",
  "request.html",
  "sent.html",
  "verify.html",
  "privacy.html",
  "accessibility.html",
  "cookies.html",
  "contact.html",
  "terms.html",
  "not-found.html",
];

const region = (name, body) =>
  `<!-- govbb:${name} — generated by scripts/build-pages.js, do not edit -->${body}\n<!-- /govbb:${name} -->`;

function regionRe(name) {
  return new RegExp(`<!-- govbb:${name}[^]*?<!-- /govbb:${name} -->`, "m");
}

function replaceRegion(html, name, body) {
  const re = regionRe(name);
  const rendered = region(name, body);
  if (re.test(html)) return html.replace(re, rendered);
  return null; // caller inserts it
}

// A region whose source declaration has been removed has to go, or it is
// frozen into the page forever — and --check would compare the generated
// output against the committed file and call the orphan "up to date".
function dropRegion(html, name) {
  const re = regionRe(name);
  return re.test(html) ? html.replace(re, "").replace(/\n[ \t]*\n[ \t]*\n/g, "\n\n") : html;
}

// Pages sit at the site root and link to each other relatively, which works on
// both Vercel (domain root) and Pages (project subpath). Kept as a seam so the
// admin pages, one level down, can reuse the same templates with "../".
const toPagePath = (s) => s.replace(/\{\{base\}\}/g, "");

function buildMain(html) {
  // One-time scaffold conversion: the old shell was
  //   <main id="main-content" class="page-main" data-breadcrumbs='…'>
  // with the content directly inside, sized by a bespoke .content-column.
  const openTag = html.match(/<main\b[^>]*class="page-main"[^>]*>/);
  if (!openTag) return html; // already converted

  const crumbAttr = openTag[0].match(/data-breadcrumbs='([^']*)'/);
  const attr = crumbAttr ? ` data-breadcrumbs='${crumbAttr[1]}'` : "";

  const replacement =
    `<main class="govbb-width-container govbb-main-wrapper" id="main-content" tabindex="-1"${attr}>\n` +
    `    <div class="govbb-grid-row">\n` +
    `      <div class="govbb-grid-column-two-thirds">`;

  html = html.replace(openTag[0], replacement);
  return html.replace(/<\/main>/, `      </div>\n    </div>\n  </main>`);
}

function buildPage(file) {
  const p = path.join(ROOT, file);
  let html = fs.readFileSync(p, "utf-8");

  html = buildMain(html);

  // The runtime injector is gone; its markup is now in the file.
  html = html.replace(/\s*<script src="chrome\.js"><\/script>/g, "");

  const top = toPagePath(skipLink + officialBanner + header + alphaBanner);
  const bottom = toPagePath(footer + runtime);

  const withTop = replaceRegion(html, "chrome-top", top);
  html =
    withTop ??
    html.replace(/(<body[^>]*>)/, `$1\n${region("chrome-top", top)}`);

  const withBottom = replaceRegion(html, "chrome-bottom", bottom);
  html =
    withBottom ??
    html.replace(/<\/body>/, `${region("chrome-bottom", bottom)}\n</body>`);

  // Breadcrumbs are declared per page on <main data-breadcrumbs>, and rendered
  // here so the trail is in the source too.
  const declared = html.match(/data-breadcrumbs='([^']*)'/);
  const crumbs = declared
    ? toPagePath(breadcrumbs(JSON.parse(declared[1])))
    : "";
  if (crumbs) {
    const withCrumbs = replaceRegion(html, "breadcrumbs", crumbs);
    html =
      withCrumbs ??
      html.replace(
        /(<main\b[^>]*>)/,
        `$1\n    ${region("breadcrumbs", crumbs)}`
      );
  } else {
    html = dropRegion(html, "breadcrumbs");
  }

  // Pages that declare data-needs-js get the JavaScript-disabled notice, so a
  // visitor without script is told what to do rather than left on a shell.
  const needs = html.match(/data-needs-js="([^"]*)"/);
  if (needs) {
    const block = toPagePath(noScript(needs[1]));
    const withNs = replaceRegion(html, "noscript", block);
    html =
      withNs ??
      html.replace(
        /(<div class="govbb-grid-column-two-thirds">)/,
        `$1\n    ${region("noscript", block)}`
      );
  } else {
    html = dropRegion(html, "noscript");
  }

  return { path: p, html };
}

const check = process.argv.includes("--check");
let changed = 0;
const stale = [];

for (const file of PAGES) {
  const { path: p, html } = buildPage(file);
  const current = fs.readFileSync(p, "utf-8");
  if (current === html) continue;
  if (check) {
    stale.push(file);
  } else {
    fs.writeFileSync(p, html);
    changed++;
  }
}

if (check) {
  if (stale.length) {
    console.error(
      `${stale.length} page(s) out of date with scripts/chrome.js:\n  ` +
        stale.join("\n  ") +
        `\nRun \`npm run build:pages\` and commit the result.`
    );
    process.exit(1);
  }
  console.log(`all ${PAGES.length} pages are up to date`);
} else {
  console.log(`chrome rendered into ${changed} of ${PAGES.length} page(s)`);
}
