// Renders the shared chrome into each page's HTML source.
//
// It used to be injected at runtime by chrome.js, so a page loaded without
// JavaScript had no header, no footer, no official banner and no skip link —
// unbranded body copy with nothing identifying it as a government service.
// GitHub Pages cannot run a server, so the only way for the chrome to survive
// with script unavailable is for it to be in the file.
//
// Idempotent: generated regions are delimited by comment markers and replaced
// on each run. `npm run check:pages` fails if a committed page has drifted.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import {
  skipLink,
  officialBanner,
  header,
  alphaBanner,
  feedback,
  footer,
  breadcrumbs,
  runtime,
  noScript,
} from "./chrome.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");

// The user-facing pages. job-letter-request.html is the superseded single-file
// prototype and is deliberately not in this list.
const PAGES = [
  "index.html",
  "request.html",
  "sent.html",
  "verify.html",
  "contact.html",
  "not-found.html",
];

const region = (name, body) =>
  `<!-- govbb:${name} — generated by scripts/build-pages.js, do not edit -->${body}\n<!-- /govbb:${name} -->`;

function regionRe(name) {
  return new RegExp(`<!-- govbb:${name}[^]*?<!-- /govbb:${name} -->`, "m");
}

function replaceRegion(html, name, body) {
  const re = regionRe(name);
  const rendered = region(name, body);
  if (re.test(html)) return html.replace(re, rendered);
  return null; // caller inserts it
}

// A region whose source declaration has been removed has to go, or it is
// frozen into the page forever — and --check would compare the generated
// output against the committed file and call the orphan "up to date".
function dropRegion(html, name) {
  const re = regionRe(name);
  return re.test(html) ? html.replace(re, "").replace(/\n[ \t]*\n[ \t]*\n/g, "\n\n") : html;
}

// Pages sit at the site root and link to each other relatively, which works on
// both Vercel (domain root) and Pages (project subpath). Kept as a seam so the
// admin pages, one level down, can reuse the same templates with "../".
const toPagePath = (s) => s.replace(/\{\{base\}\}/g, "");

// Give the request form a real action and method so it works without script.
// app.js calls preventDefault() and uses the JSON endpoint when script runs,
// so this is the fallback rather than the normal path.
//
// Same-origin on purpose. An absolute URL to the deploy would also let the
// GitHub Pages demo submit, but it would mean a local no-JS submit posting to
// production and issuing a real letter, which is not a trade worth making to
// paper over a static host that structurally cannot process a POST.
function buildForm(html) {
  return html.replace(
    /<form id="request-form"[^>]*novalidate>/,
    `<form id="request-form" method="post" action="/api/request-letter-form" novalidate>`
  );
}

// Page shape follows the platform. gov-bb's apps/landing renders every service
// page as
//
//     <div class="govbb-width-container govbb-main-wrapper">
//       <div class="govbb-prose">…</div>
//     </div>
//
// (routes/$.tsx and components/markdown/MarkdownContent.tsx), with the body
// authored as markdown, so headings, paragraphs and lists arrive as bare
// elements and govbb-prose sizes them and owns the rhythm between them.
//
// This service hand-writes its HTML rather than living in the monorepo, but it
// uses the same containers so the CSS behaves identically. That replaced a
// bespoke .page-flow, which had re-implemented prose's rhythm and its reading
// measure by hand.
function buildMain(html) {
  const openTag = html.match(/<main\b[^>]*>/);
  if (!openTag) return html;

  const keep = (name, quote = "'") => {
    const m = openTag[0].match(new RegExp(`${name}=${quote}([^${quote}]*)${quote}`));
    return m ? ` ${name}=${quote}${m[1]}${quote}` : "";
  };
  const attrs = keep("data-breadcrumbs") + keep("data-needs-js", '"');

  html = html.replace(
    openTag[0],
    `<main class="govbb-width-container govbb-main-wrapper" id="main-content" tabindex="-1"${attrs}>`
  );

  // Column, then prose — matching the chain alpha.gov.bb actually renders:
  //
  //   govbb-width-container govbb-main-wrapper   1070px
  //     lg:grid lg:grid-cols-3                   1070px
  //       lg:col-span-2                           692px
  //         govbb-prose                           692px
  //
  // The platform builds that column with Tailwind, which is why the published
  // templates show a flat shape and /styles/layout.md does not — measured on a
  // live service page rather than inferred. govbb-grid-column-two-thirds is
  // span 8 of 12, which lands within a couple of pixels of the same width, so
  // this is the same layout expressed in design-system classes.
  // Insert the column and prose. Insert-only — never replace an existing
  // </div>, or a page that closes another container just before </main>
  // (verify.html's #verify-root) loses its own closing tag.
  if (!/govbb-grid-row/.test(html)) {
    html = html
      .replace(
        /(<main\b[^>]*>)\n/,
        '$1\n    <div class="govbb-grid-row">\n      <div class="govbb-grid-column-two-thirds">\n        <div class="govbb-prose">\n'
      )
      .replace(/\n(\s*)<\/main>/, "\n        </div>\n      </div>\n    </div>\n$1</main>");
  }

  return html;
}

function buildPage(file) {
  const p = path.join(ROOT, file);
  let html = fs.readFileSync(p, "utf-8");

  html = buildMain(html);
  html = buildForm(html);

  // The runtime injector is gone; its markup is now in the file.
  html = html.replace(/\s*<script src="chrome\.js"><\/script>/g, "");

  const top = toPagePath(skipLink + officialBanner + header + alphaBanner);
  // Feedback sits between main and the footer, as HelpfulBox does on the
  // platform: its own width container, after the main wrapper.
  const bottom = toPagePath(feedback + footer + runtime);

  const withTop = replaceRegion(html, "chrome-top", top);
  html =
    withTop ??
    html.replace(/(<body[^>]*>)/, `$1\n${region("chrome-top", top)}`);

  const withBottom = replaceRegion(html, "chrome-bottom", bottom);
  html =
    withBottom ??
    html.replace(/<\/body>/, `${region("chrome-bottom", bottom)}\n</body>`);

  // Breadcrumbs are declared per page on <main data-breadcrumbs>, and rendered
  // here so the trail is in the source too.
  const declared = html.match(/data-breadcrumbs='([^']*)'/);
  const crumbs = declared
    ? toPagePath(breadcrumbs(JSON.parse(declared[1])))
    : "";
  if (crumbs) {
    const withCrumbs = replaceRegion(html, "breadcrumbs", crumbs);
    html =
      withCrumbs ??
      html.replace(
        /(<main\b[^>]*>)/,
        `$1\n    ${region("breadcrumbs", crumbs)}`
      );
  } else {
    html = dropRegion(html, "breadcrumbs");
  }

  // Pages that declare data-needs-js get the JavaScript-disabled notice, so a
  // visitor without script is told what to do rather than left on a shell.
  const needs = html.match(/data-needs-js="([^"]*)"/);
  if (needs) {
    const block = toPagePath(noScript(needs[1]));
    const withNs = replaceRegion(html, "noscript", block);
    // Anchor on <main>, not on a grid column — the columns went when the page
    // shape was flattened to match the templates, and this insertion silently
    // did nothing for a while because its anchor no longer existed.
    html =
      withNs ??
      html.replace(/(<main\b[^>]*>)/, `$1\n    ${region("noscript", block)}`);
  } else {
    html = dropRegion(html, "noscript");
  }

  return { path: p, html };
}

const check = process.argv.includes("--check");
let changed = 0;
const stale = [];

for (const file of PAGES) {
  const { path: p, html } = buildPage(file);
  const current = fs.readFileSync(p, "utf-8");
  if (current === html) continue;
  if (check) {
    stale.push(file);
  } else {
    fs.writeFileSync(p, html);
    changed++;
  }
}

if (check) {
  if (stale.length) {
    console.error(
      `${stale.length} page(s) out of date with scripts/chrome.js:\n  ` +
        stale.join("\n  ") +
        `\nRun \`npm run build:pages\` and commit the result.`
    );
    process.exit(1);
  }
  console.log(`all ${PAGES.length} pages are up to date`);
} else {
  console.log(`chrome rendered into ${changed} of ${PAGES.length} page(s)`);
}
